/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

const char *version_string = "1.14";
const char *compilation_string = "arm-linux-gcc -std=gnu99 -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/usr/local/etc/wgetrc\" -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../lib -I../lib -O2 -Wall";
const char *link_string = "arm-linux-gcc -std=gnu99 -O2 -Wall -lz ftp-opie.o ../lib/libgnu.a";
